version: '3.3'

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: appsemble
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '2345:80'
