name: Waarnemingen
defaultPage: Maak waarneming

theme:
  splashColor: '#FFFFFF'
  themeColor: '#eb0000'
  primaryColor: '#eb0000'

resources:
  waarneming:
    schema:
      type: object
      required:
        - proces
        - status
        - kanaal
      properties:
        notities:
          title: Notities
        fotos:
          title: Foto's
          type: array
          items:
            type: string
            appsembleFile:
              type:
                - image/jpeg
        proces:
          title: Proces
          enum:
            - Afval
            - Handhaving
            - Stadswerken
            - Groen
        locatie:
          title: Locatie
          type: object
          required:
            - latitude
            - longitude
          properties:
            latitude:
              type: number
            longitude:
              type: number
        status:
          title: Status
          enum:
            - open
            - in-behandeling
            - opgelost
        kanaal:
          title: Kanaal
          enum:
            - Centraal
            - Zuid
            - Noord

  waarnemingReply:
    references:
      waarnemingId: waarneming
    schema:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          minLength: 1

authentication:
  - method: email
    url: /api/oauth/token
    clientId: appsemble-studio
    scope: apps:read

pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        version: 0.9.4
        parameters:
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
            - name: type
              label: Type
              enum:
                - value: Bijplaatsing
                - value: Kapotte container
            - name: proces
              label: Proces
              enum:
                - value: Afval
                - value: Handhaving
                - value: Stadswerken
                - value: Groen
            - name: kanaal
              label: Kanaal
              enum:
                - value: Centraal
                - value: Noord
                - value: Zuid
            - name: status
              type: hidden
              defaultValue: open
            - name: notities
              label: Notities
              placeholder: Bijv. Er ligt een fiets in de bosjes.
              type: string
              multiline: true
            - name: fotos
              label: Foto’s
              type: file
              accept:
                - image/jpeg
              repeated: true
        actions:
          onSubmit:
            type: dialog
            fullscreen: true
            blocks:
              - type: '@amsterdam/splash'
                version: 0.9.4
                actions:
                  onLoad:
                    type: resource.create
                    resource: waarneming
                  onError:
                    type: dialog.error
                  onSuccess:
                    type: link
                    to: Overzichtskaart

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        version: 0.9.4
        parameters:
          latitude: locatie.latitude
          longitude: locatie.longitude
        actions:
          onMarkerClick:
            type: link
            to: Waarneming details
          onLoad:
            type: resource.query
            resource: waarneming
            query:
              $orderby: '$created desc'
              $top: 50
      - type: action-button
        version: 0.9.4
        actions:
          onClick:
            type: link
            to: Maak waarneming

  - name: Waarnemingen lijst
    scope:
      - '*'
    blocks:
      - type: filter
        version: 0.9.4
        parameters:
          refreshTimeout: 30
          event: updateWaarnemingen
          highlight: kanaal
          fields:
            - name: kanaal
              emptyLabel: Alle kanalen
              enum:
                - value: Centraal
                - value: Noord
                - value: Zuid
            - name: created
              label: Datum
              type: date
              icon: calendar-alt
              range: true
            - name: status
              label: Status
              icon: cogs
              enum:
                - value: open
                  label: Open
                - value: in-behandeling
                  label: In behandeling
                - value: opgelost
                  label: Opgelost
        actions:
          onLoad:
            type: resource.query
            resource: waarneming
            query:
              $orderby: '$created desc'
              $top: 50

      - type: feed
        version: 0.9.4
        parameters:
          listen: updateWaarnemingen
          title: type
          subtitle: proces
          heading: $created|date
          picture: fotos.0
          pictureBase: /api/assets
          description: notities
          reply:
            content: content
            author: author
            parentId: waarnemingId
          longitude: locatie.longitude
          latitude: locatie.latitude
        actions:
          onLoadReply:
            type: resource.query
            resource: waarnemingReply
          onSubmitReply:
            type: resource.create
            resource: waarnemingReply
          onAvatarClick:
            type: dialog
            blocks:
              - type: '@amsterdam/action'
                version: 0.9.4
                actions:
                  onSubmit:
                    type: resource.update
                    resource: waarneming
                  onSuccess:
                    type: dialog.ok
                  onError:
                    type: dialog.error
                parameters:
                  title: VOER ACTIE UIT
                  fields:
                    - name: status
                      label: pak waarneming op
                      icon: cog
                      color: '#FFFFFF'
                      backgroundColor: '#00AEEF'
                      value: in-behandeling
                    - name: status
                      label: meld als opgelost
                      icon: check
                      color: '#FFFFFF'
                      backgroundColor: '#006502'
                      value: opgelost
                    - name: proces
                      label: routeer naar
                      icon: paper-plane
                      color: '#FFFFFF'
                      backgroundColor: '#006502'
                      enum:
                        - value: Afval
                        - value: Handhaving
                        - value: Stadswerken
                        - value: Groen
      - type: action-button
        version: 0.9.4
        actions:
          onClick:
            type: link
            to: Maak waarneming
  - name: Waarneming details
    scope:
      - '*'
    parameters:
      - id
    blocks:
      - type: detail-viewer
        version: 0.9.4
        parameters:
          fileBase: /api/assets
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
              longitude: longitude
              latitude: latitude
            - name: proces
              label: Proces
            - name: kanaal
              label: Kanaal
            - name: status
              label: Status
            - name: notities
              label: Notities
            - name: fotos
              label: Foto's
              type: file
              repeated: true
        actions:
          onLoad:
            type: resource.get
            resource: waarneming
