apiVersion: v1
name: appsemble
version: 0.9.4
description: The official Helm chart for Appsemble.
icon: https://gitlab.com/uploads/-/system/project/avatar/7050597/bitmap.png
home: https://appsemble.com
sources:
  - https://gitlab.com/appsemble/appsemble
appVersion: 0.9.4
