replicaCount: 1

image:
  repository: appsemble/appsemble
  tag: null
  pullPolicy: IfNotPresent

app: appsemble
nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: ''
  tls:
    {}
    # secretName: chart-example-tls

resources:
  {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

smtpSecret: smtp

sentrySecret: {}

migrateTo: {}

global:
  postgresql:
    postgresqlDatabase: appsemble
    postgresqlUsername: appsemble
    servicePort: 5432
    existingSecret: appsemble-postgresql-secret

postgresql:
  fullnameOverride: appsemble-postgresql
  persistence:
    enabled: false

postgresSSL: null
