apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "docs.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "docs.chart" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.url | trimPrefix "https://" }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.url | trimPrefix "https://" }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "docs.fullname" . }}
              servicePort: http
